apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongo-deploy
    labels:
        name: mongo-deploy
        app: microservice
spec:
    replicas: 1
    selector:
        matchLabels:
            app: microservice-libreria
            name: mongo-pod
    template:
        metadata:
            name: mongo-pod
            labels:
                app: microservice-libreria
                name: mongo-pod
        spec:
            containers:
            - name: mongo
              image: mongo:latest
              command:
               - /bin/bash
               - -c
              ports:
               - containerPort: 27017
              env:
               - name: MONGO_INITDB_ROOT_USERNAME
                 value: "blondonogarcia"
               - name: MONGO_INITDB_ROOT_PASSWORD
                 value: "Bryan1224."